/* מערכת השיבוצים של מעון הדס — גרסה 0.2.0 */
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const DAY_NAMES=['ראשון','שני','שלישי','רביעי','חמישי','שישי','שבת'];
const ROLE_LABELS={admin:'מנהלת מעון',scheduler:'אחראית שיבוץ',employee:'עובדת'};
const SHIFT_ROLE_LABELS={teacher:'גננת',lead:'מובילה',staff:'אשת צוות',replacement:'מחליפה'};
const SHIFT_STATUS_LABELS={draft:'טיוטה',temporary:'זמני',final:'סופי'};
const REQUEST_LABELS={leave:'חופשה',day_off:'יום חופשי',late_start:'התחלה מאוחרת',early_finish:'סיום מוקדם',sick:'מחלה',swap:'החלפת שיבוץ',other:'אחר'};
const REQUEST_STATUS_LABELS={pending:'ממתינה',approved:'אושרה',rejected:'נדחתה',applied:'הוזרמה',cancelled:'בוטלה'};
const ATTENDANCE_LABELS={scheduled:'טרם עודכן',present:'נכחה',late:'איחרה',left_early:'יצאה מוקדם',absent:'נעדרה',sick:'מחלה',replacement:'החליפה עובדת'};
const EVENT_LABELS={holiday:'חופשה/חג',meeting:'ישיבה',training:'הדרכה',birthday:'יום הולדת',activity:'פעילות',other:'אחר'};
const PRIORITY_LABELS={normal:'רגילה',important:'חשובה',urgent:'דחופה'};

const state={
  config:null,storageClient:null,csrfToken:'',profile:null,classes:[],employees:[],constraints:[],settings:{},
  shifts:[],todayShifts:[],attendance:[],requests:[],acknowledgements:[],announcements:[],announcementReads:[],
  tasks:[],taskAssignees:[],calendarEvents:[],documents:[],weekStart:startOfWeek(new Date()),attendanceDate:dateISO(new Date()),
  realtimeChannel:null,reloadTimer:null,pollTimer:null,suggestionsContext:null,
};

function escapeHtml(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function dateISO(date){const d=new Date(date);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function parseLocalDate(value){return new Date(`${value}T12:00:00`);}
function addDays(date,days){const d=new Date(date);d.setDate(d.getDate()+days);return d;}
function startOfWeek(date){const d=new Date(date);d.setHours(12,0,0,0);d.setDate(d.getDate()-d.getDay());return d;}
function formatDate(value,options={day:'2-digit',month:'2-digit',year:'numeric'}){return new Intl.DateTimeFormat('he-IL',options).format(typeof value==='string'?parseLocalDate(value):value);}
function trimTime(value){return value?String(value).slice(0,5):'';}
function timeToMinutes(value){if(!value)return 0;const [h,m]=String(value).slice(0,5).split(':').map(Number);return h*60+m;}
function overlaps(aStart,aEnd,bStart,bEnd){return timeToMinutes(aStart)<timeToMinutes(bEnd)&&timeToMinutes(aEnd)>timeToMinutes(bStart);}
function isManager(){return ['admin','scheduler'].includes(state.profile?.role);}
function employeeById(id){return state.employees.find(item=>item.id===id);}
function classById(id){return state.classes.find(item=>item.id===id);}
function showToast(message,type=''){const toast=$('#toast');toast.textContent=message;toast.className=`toast ${type}`.trim();clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.add('hidden'),3800);}
function setScreen(id){for(const screen of ['loadingScreen','loginScreen','passwordScreen','appShell'])$(`#${screen}`).classList.toggle('hidden',screen!==id);}
function setBusy(button,busy,text='שומר…'){if(!button)return;if(busy){button.dataset.originalText=button.textContent;button.disabled=true;button.textContent=text;}else{button.disabled=false;button.textContent=button.dataset.originalText||button.textContent;}}
function formObject(form){return Object.fromEntries(new FormData(form).entries());}
function toIsoDateTime(local){return local?new Date(local).toISOString():null;}

async function apiFetch(url,options={}){
  const method=options.method||'GET';
  const headers={Accept:'application/json',...(options.headers||{})};
  if(options.body!==undefined){headers['Content-Type']='application/json';}
  if(method!=='GET'&&state.csrfToken)headers['X-CSRF-Token']=state.csrfToken;
  const response=await fetch(url,{method,headers,credentials:'same-origin',cache:'no-store',body:options.body===undefined?undefined:JSON.stringify(options.body)});
  let data={};try{data=await response.json();}catch{}
  if(response.status===401){state.profile=null;setScreen('loginScreen');throw new Error(data.error||'ההתחברות פגה');}
  if(!response.ok){const error=new Error(data.error||'הפעולה נכשלה');error.data=data;error.status=response.status;throw error;}
  return data;
}

async function init(){
  bindEvents();
  try{
    const configResponse=await fetch('/api/config',{cache:'no-store'});state.config=await configResponse.json();
    if(!configResponse.ok)throw new Error(state.config.error||'לא ניתן לטעון הגדרות');
    if(window.supabase){state.storageClient=window.supabase.createClient(state.config.supabaseUrl,state.config.supabasePublishableKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});}
    try{
      const me=await apiFetch('/api/auth-me');state.csrfToken=me.csrfToken;state.profile=me.profile;
      if(state.profile.must_change_password)return setScreen('passwordScreen');
      await enterApp();
    }catch(error){if(error.status!==401)console.warn(error);setScreen('loginScreen');}
  }catch(error){setScreen('loginScreen');showToast(error.message,'error');}
}

function bindEvents(){
  $('#loginForm').addEventListener('submit',handleLogin);$('#passwordForm').addEventListener('submit',handlePasswordChange);$('#logoutBtn').addEventListener('click',logout);
  $$('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>switchTab(btn.dataset.tab)));
  $('#prevWeekBtn').addEventListener('click',()=>setWeek(addDays(state.weekStart,-7)));$('#nextWeekBtn').addEventListener('click',()=>setWeek(addDays(state.weekStart,7)));$('#todayWeekBtn').addEventListener('click',()=>setWeek(startOfWeek(new Date())));
  $('#copyWeekBtn').addEventListener('click',copyPreviousWeek);$('#addShiftBtn').addEventListener('click',()=>openShiftDialog());
  $('#publishTemporaryBtn').addEventListener('click',()=>publishWeek('temporary'));$('#publishFinalBtn').addEventListener('click',()=>publishWeek('final'));$('#ackScheduleBtn').addEventListener('click',acknowledgeSchedule);
  $('#settingsBtn').addEventListener('click',openSettings);$('#printBtn').addEventListener('click',()=>window.print());$('#imageBtn').addEventListener('click',downloadScheduleImage);
  $('#attendanceDate').addEventListener('change',async(e)=>{state.attendanceDate=e.target.value;await refreshAll();});
  $('#newEmployeeBtn').addEventListener('click',()=>openEmployeeDialog());$('#newRequestBtn').addEventListener('click',openRequestDialog);$('#newAnnouncementBtn').addEventListener('click',()=>openDialogForm('#announcementDialog','#announcementForm'));$('#newTaskBtn').addEventListener('click',()=>openTaskDialog());$('#newCalendarBtn').addEventListener('click',()=>openCalendarDialog());$('#newDocumentBtn').addEventListener('click',()=>openDialogForm('#documentDialog','#documentForm'));
  $('#shiftForm').addEventListener('submit',saveShift);$('#employeeForm').addEventListener('submit',saveEmployee);$('#requestForm').addEventListener('submit',saveRequest);$('#announcementForm').addEventListener('submit',saveAnnouncement);$('#taskForm').addEventListener('submit',saveTask);$('#calendarForm').addEventListener('submit',saveCalendarEvent);$('#documentForm').addEventListener('submit',saveDocument);$('#settingsForm').addEventListener('submit',saveSettings);
  $('#requestForm [name="request_type"]').addEventListener('change',updateRequestFields);$('#requestForm [name="target_employee_id"]').addEventListener('change',populateTargetShifts);$('#requestForm [name="shift_id"]').addEventListener('change',syncRequestDateFromShift);$('#taskForm [name="target_type"]').addEventListener('change',populateTaskTarget);
  $$('.close-dialog').forEach(btn=>btn.addEventListener('click',()=>btn.closest('dialog').close()));
  $('#scheduleExport').addEventListener('click',handleScheduleClick);$('#employeesList').addEventListener('click',handleEmployeeClick);$('#requestsList').addEventListener('click',handleRequestClick);$('#attendanceList').addEventListener('click',handleAttendanceClick);$('#announcementsList').addEventListener('click',handleAnnouncementClick);$('#tasksList').addEventListener('click',handleTaskClick);$('#calendarList').addEventListener('click',handleCalendarClick);$('#documentsList').addEventListener('click',handleDocumentClick);$('#suggestionsList').addEventListener('click',handleSuggestionClick);
}

async function handleLogin(event){event.preventDefault();const button=event.currentTarget.querySelector('button');setBusy(button,true,'מתחברת…');try{const body=formObject(event.currentTarget);const data=await apiFetch('/api/auth-login',{method:'POST',body});state.csrfToken=data.csrfToken;state.profile=data.profile;if(state.profile.must_change_password)setScreen('passwordScreen');else await enterApp();}catch(error){showToast(error.message,'error');}finally{setBusy(button,false);}}
async function handlePasswordChange(event){event.preventDefault();const body=formObject(event.currentTarget);if(body.password!==body.confirmPassword)return showToast('הסיסמאות אינן זהות','error');const button=event.currentTarget.querySelector('button');setBusy(button,true);try{const data=await apiFetch('/api/auth-change-password',{method:'POST',body:{password:body.password}});state.csrfToken=data.csrfToken;state.profile=data.profile;await enterApp();showToast('הסיסמה נשמרה','success');}catch(error){showToast(error.message,'error');}finally{setBusy(button,false);}}
async function logout(){try{await apiFetch('/api/auth-logout',{method:'POST',body:{}});}catch{}state.profile=null;state.csrfToken='';if(state.realtimeChannel&&state.storageClient)state.storageClient.removeChannel(state.realtimeChannel);clearInterval(state.pollTimer);setScreen('loginScreen');}

async function enterApp(){setScreen('appShell');applyPermissions();$('#attendanceDate').value=state.attendanceDate;await refreshAll();subscribeRealtime();}
function applyPermissions(){$$('.manager-only').forEach(el=>el.classList.toggle('hidden',!isManager()));$$('.employee-only').forEach(el=>el.classList.toggle('hidden',isManager()));$('#userName').textContent=state.profile.full_name;$('#userRole').textContent=`${ROLE_LABELS[state.profile.role]||state.profile.role} · ${state.profile.job_title}`;}
function switchTab(tab){$$('.nav-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.tab===tab));$$('.panel').forEach(panel=>panel.classList.toggle('active',panel.id===`${tab}Panel`));}
async function setWeek(date){state.weekStart=startOfWeek(date);await refreshAll();}

async function refreshAll(){
  try{
    const data=await apiFetch(`/api/data?week_start=${dateISO(state.weekStart)}&attendance_date=${state.attendanceDate}`);
    Object.assign(state,{profile:data.profile,classes:data.classes,employees:data.employees,constraints:data.constraints,settings:data.settings,shifts:data.shifts,todayShifts:data.todayShifts||[],attendance:data.attendance,requests:data.requests,acknowledgements:data.acknowledgements,announcements:data.announcements,announcementReads:data.announcementReads,tasks:data.tasks,taskAssignees:data.taskAssignees,calendarEvents:data.calendarEvents,documents:data.documents});
    applyPermissions();populateSelects();renderAll();
  }catch(error){showToast(error.message,'error');}
}

function subscribeRealtime(){
  if(!state.storageClient)return;
  if(state.realtimeChannel)state.storageClient.removeChannel(state.realtimeChannel);
  state.realtimeChannel=state.storageClient.channel('hadas-public-refresh').on('postgres_changes',{event:'INSERT',schema:'public',table:'hadas_realtime_events'},()=>{
    clearTimeout(state.reloadTimer);state.reloadTimer=setTimeout(()=>refreshAll(),450);
  }).subscribe(status=>{
    const live=$('#liveStatus');
    if(status==='SUBSCRIBED')live.innerHTML='<span></span> מתעדכן בזמן אמת';
    else if(['CHANNEL_ERROR','TIMED_OUT'].includes(status))live.textContent='עדכון חי נותק — קיים רענון אוטומטי';
  });
  clearInterval(state.pollTimer);state.pollTimer=setInterval(()=>refreshAll(),60000);
}

function populateSelects(){
  const classOptions=state.classes.filter(c=>c.active).map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');
  const employeeOptions=state.employees.filter(e=>e.active).map(e=>`<option value="${e.id}">${escapeHtml(e.full_name)} — ${escapeHtml(e.job_title)}</option>`).join('');
  $('#shiftForm [name="class_id"]').innerHTML=classOptions;$('#shiftForm [name="employee_id"]').innerHTML=employeeOptions;
  $('#employeeForm [name="primary_class_id"]').innerHTML=`<option value="">ללא כיתה קבועה</option>${classOptions}`;
  $('#requestForm [name="target_employee_id"]').innerHTML=`<option value="">בחרי עובדת</option>${state.employees.filter(e=>e.active&&e.id!==state.profile.id).map(e=>`<option value="${e.id}">${escapeHtml(e.full_name)}</option>`).join('')}`;
  for(const form of ['announcementForm','calendarForm','documentForm'])$(`#${form} [name="class_id"]`).innerHTML=`<option value="">${form==='announcementForm'?'כל המעון':'ללא'}</option>${classOptions}`;
  populateTaskTarget();
}

function renderAll(){renderDashboard();renderSchedule();renderRequests();renderAttendance();renderAnnouncements();renderTasks();renderCalendar();renderDocuments();if(isManager())renderEmployees();}

function shiftLineHtml(shift){const employee=employeeById(shift.employee_id);return `<div class="employee-line"><span><strong>${escapeHtml(employee?.full_name||'עובדת')}</strong><small>${SHIFT_ROLE_LABELS[shift.shift_role]}${shift.public_note?` · ${escapeHtml(shift.public_note)}`:''}</small></span><span>${trimTime(shift.start_time)}–${trimTime(shift.end_time)}</span></div>`;}
function renderDashboard(){
  const today=dateISO(new Date());const shifts=state.todayShifts.length?state.todayShifts:state.shifts.filter(s=>s.shift_date===today);const staffed=new Set(shifts.map(s=>s.employee_id));
  const my=shifts.filter(s=>s.employee_id===state.profile.id);const pending=state.requests.filter(r=>r.status==='pending').length;const dueTasks=state.taskAssignees.filter(a=>a.employee_id===state.profile.id&&a.status!=='done').length;const unread=state.announcements.filter(a=>!state.announcementReads.some(r=>r.announcement_id===a.id&&r.employee_id===state.profile.id)).length;
  const classCards=state.classes.filter(c=>c.active).map(c=>{const rows=shifts.filter(s=>s.class_id===c.id);const result=coverageFor(rows);return `<article class="class-card"><div class="card-heading"><h3>${escapeHtml(c.name)}</h3><span class="status-chip ${result.ok?'ok':'error'}">${result.ok?'תקין':'דורש טיפול'}</span></div>${rows.length?rows.map(shiftLineHtml).join(''):'<div class="empty-state">אין שיבוץ להיום</div>'}<p class="small-note">${result.count} משובצות · ${result.closing} בסגירה · ${result.leader?'יש גננת/מובילה':'חסרה גננת/מובילה'}</p></article>`;}).join('');
  $('#dashboardPanel').innerHTML=`<div class="section-heading"><div><h2>שלום ${escapeHtml(state.profile.full_name)}</h2><p class="muted">${formatDate(today,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div></div><div class="dashboard-grid"><article class="summary-card"><span class="caption">השיבוץ שלי היום</span><span class="metric">${my.length||'—'}</span><small>${my.length?my.map(s=>`${classById(s.class_id)?.name||''} ${trimTime(s.start_time)}–${trimTime(s.end_time)}`).join(' · '):'אין שיבוץ'}</small></article><article class="summary-card"><span class="caption">עובדות משובצות</span><span class="metric">${staffed.size}</span><small>בכל המעון היום</small></article><article class="summary-card"><span class="caption">בקשות ממתינות</span><span class="metric">${pending}</span><small>${isManager()?'דורשות טיפול':'הבקשות שלך והחלפות'}</small></article><article class="summary-card"><span class="caption">משימות פתוחות</span><span class="metric">${dueTasks}</span><small>${unread} הודעות שלא נקראו</small></article></div><div class="section-heading" style="margin-top:24px"><div><h2>מצב הכיתות היום</h2></div></div><div class="dashboard-grid">${classCards}</div><article class="summary-card release-card" style="margin-top:20px"><strong>מה חדש בגרסה 0.2.0</strong><p>כניסה ללא מייל, ניהול עובדות, שיבוץ חי, הצעת מחליפות, הודעות, משימות, לוח שנה ומסמכים פרטיים.</p></article>`;
}
function coverageFor(rows){const count=new Set(rows.map(s=>s.employee_id)).size;const closingTime=trimTime(state.settings.closing_time||'15:30');const closing=new Set(rows.filter(s=>timeToMinutes(s.end_time)>=timeToMinutes(closingTime)).map(s=>s.employee_id)).size;const leader=rows.some(s=>['teacher','lead'].includes(s.shift_role));return{count,closing,leader,ok:count>=Number(state.settings.required_staff||4)&&closing>=Number(state.settings.closing_required_staff||3)&&leader};}

function weekDates(){return Array.from({length:6},(_,i)=>addDays(state.weekStart,i));}
function validateScheduleClient(){
  const errors=[],warnings=[];const open=timeToMinutes(state.settings.opening_time||'07:30'),close=timeToMinutes(state.settings.closing_time||'15:30'),slot=Number(state.settings.validation_slot_minutes||30),closingWindow=Number(state.settings.closing_window_minutes||30);
  for(const date of weekDates().map(dateISO))for(const c of state.classes.filter(x=>x.active))for(let m=open;m<close;m+=slot){const end=Math.min(m+slot,close);const startT=`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`,endT=`${String(Math.floor(end/60)).padStart(2,'0')}:${String(end%60).padStart(2,'0')}`;const rows=state.shifts.filter(s=>s.shift_date===date&&s.class_id===c.id&&overlaps(s.start_time,s.end_time,startT,endT));const count=new Set(rows.map(s=>s.employee_id)).size;const required=m>=close-closingWindow?Number(state.settings.closing_required_staff||3):Number(state.settings.required_staff||4);if(count<required)errors.push(`${c.name} · ${formatDate(date)} · ${startT}: ${count}/${required} נשות צוות`);if(!rows.some(s=>['teacher','lead'].includes(s.shift_role)))errors.push(`${c.name} · ${formatDate(date)} · ${startT}: חסרה גננת או מובילה`);}
  for(const employee of state.employees.filter(e=>e.active&&e.weekly_hours!=null)){const mins=state.shifts.filter(s=>s.employee_id===employee.id).reduce((sum,s)=>sum+timeToMinutes(s.end_time)-timeToMinutes(s.start_time),0);const delta=Math.round((mins/60-Number(employee.weekly_hours))*10)/10;if(Math.abs(delta)>=2)warnings.push(`${employee.full_name}: ${delta>0?'חריגה':'חסרות'} ${Math.abs(delta)} שעות`);}
  return{errors:[...new Set(errors)],warnings:[...new Set(warnings)]};
}
function renderSchedule(){
  const dates=weekDates();$('#weekLabel').textContent=`${formatDate(dates[0])}–${formatDate(dates[5])}`;const validation=validateScheduleClient();$('#scheduleWarnings').innerHTML=`<div class="warning-summary"><span class="warning-pill ${validation.errors.length?'error':'ok'}">${validation.errors.length?`${validation.errors.length} שגיאות`:'אין שגיאות'}</span><span class="warning-pill ${validation.warnings.length?'warn':'ok'}">${validation.warnings.length?`${validation.warnings.length} התראות שעות`:'שעות תקינות'}</span></div>${validation.errors.slice(0,8).map(x=>`<div class="warning-item error">${escapeHtml(x)}</div>`).join('')}${validation.warnings.slice(0,6).map(x=>`<div class="warning-item warn">${escapeHtml(x)}</div>`).join('')}`;
  const header=dates.map(d=>`<th class="schedule-day-header">${DAY_NAMES[d.getDay()]}<small>${formatDate(d,{day:'2-digit',month:'2-digit'})}</small></th>`).join('');
  const rows=state.classes.filter(c=>c.active).map(c=>`<tr><td class="class-name">${escapeHtml(c.name)}</td>${dates.map(d=>{const date=dateISO(d);const shifts=state.shifts.filter(s=>s.class_id===c.id&&s.shift_date===date);return `<td><div class="schedule-cell">${shifts.map(s=>`<article class="shift-item shift-row status-${s.status}" data-shift-id="${s.id}"><strong>${escapeHtml(employeeById(s.employee_id)?.full_name||'')}</strong><small>${SHIFT_ROLE_LABELS[s.shift_role]} · ${trimTime(s.start_time)}–${trimTime(s.end_time)}</small>${s.public_note?`<small>${escapeHtml(s.public_note)}</small>`:''}<span class="status-chip ${s.status}">${SHIFT_STATUS_LABELS[s.status]}</span>${isManager()?`<button class="delete-shift" data-action="delete-shift" data-id="${s.id}" title="מחיקה">×</button>`:''}</article>`).join('')||'<div class="empty-state">אין שיבוץ</div>'}${isManager()?`<button class="ghost-btn small-btn" data-action="suggest" data-date="${date}" data-class-id="${c.id}">מציאת מחליפה</button>`:''}</div></td>`;}).join('')}</tr>`).join('');
  $('#scheduleExport').innerHTML=`<table class="schedule-table"><thead><tr><th class="class-name">כיתה</th>${header}</tr></thead><tbody>${rows}</tbody></table>`;
}

async function handleScheduleClick(event){const deleteBtn=event.target.closest('[data-action="delete-shift"]');if(deleteBtn){event.stopPropagation();if(confirm('למחוק את השיבוץ?')){await apiFetch('/api/shifts',{method:'DELETE',body:{id:deleteBtn.dataset.id}});await refreshAll();}return;}const suggest=event.target.closest('[data-action="suggest"]');if(suggest)return showSuggestions(suggest.dataset.date,suggest.dataset.classId);const item=event.target.closest('[data-shift-id]');if(item&&isManager())openShiftDialog(state.shifts.find(s=>s.id===item.dataset.shiftId));}
function openShiftDialog(shift={}){const form=$('#shiftForm');form.reset();form.elements.id.value=shift.id||'';form.elements.shift_date.value=shift.shift_date||dateISO(state.weekStart);form.elements.class_id.value=shift.class_id||state.classes[0]?.id||'';form.elements.employee_id.value=shift.employee_id||state.employees.find(e=>e.active)?.id||'';form.elements.start_time.value=trimTime(shift.start_time)||'07:30';form.elements.end_time.value=trimTime(shift.end_time)||'15:30';form.elements.shift_role.value=shift.shift_role||'staff';form.elements.status.value=shift.status||'draft';form.elements.public_note.value=shift.public_note||'';form.elements.override_day_off.value='false';$('#shiftDialog').showModal();}
async function saveShift(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[value="default"]'),data=formObject(form);data.override_day_off=data.override_day_off==='true';setBusy(button,true);try{try{await apiFetch('/api/shifts',{method:data.id?'PATCH':'POST',body:data});}catch(error){if(error.status===409&&/יום החופשי/.test(error.message)&&confirm(`${error.message}\nלשמור בכל זאת?`)){data.override_day_off=true;await apiFetch('/api/shifts',{method:data.id?'PATCH':'POST',body:data});}else throw error;}$('#shiftDialog').close();await refreshAll();showToast('השיבוץ נשמר','success');}catch(error){showToast(error.message,'error');}finally{setBusy(button,false);}}
async function publishWeek(status,force=false){try{const data=await apiFetch('/api/shifts',{method:'POST',body:{action:'publish',week_start:dateISO(state.weekStart),status,force}});showToast(status==='final'?'השיבוץ פורסם כסופי':'השיבוץ פורסם כזמני','success');await refreshAll();return data;}catch(error){if(status==='temporary'&&error.data?.canForce&&confirm(`${error.message}\nלפרסם זמנית למרות השגיאות?`))return publishWeek(status,true);showToast(error.message,'error');}}
async function copyPreviousWeek(){if(!confirm('להעתיק את השיבוץ מהשבוע הקודם כטיוטה?'))return;try{await apiFetch('/api/shifts',{method:'POST',body:{action:'copy_previous',week_start:dateISO(state.weekStart)}});await refreshAll();showToast('השבוע הועתק','success');}catch(error){if(/כבר קיימים/.test(error.message)&&confirm('כבר קיימים שיבוצים. למחוק אותם ולהעתיק מחדש?')){await apiFetch('/api/shifts',{method:'POST',body:{action:'copy_previous',week_start:dateISO(state.weekStart),force:true}});await refreshAll();}else showToast(error.message,'error');}}
async function acknowledgeSchedule(){try{await apiFetch('/api/shifts',{method:'POST',body:{action:'ack',week_start:dateISO(state.weekStart)}});await refreshAll();showToast('אישור הקריאה נשמר','success');}catch(error){showToast(error.message,'error');}}
async function downloadScheduleImage(){if(!window.html2canvas)return showToast('רכיב שמירת התמונה לא נטען','error');const canvas=await window.html2canvas($('#scheduleExport'),{scale:1.5,backgroundColor:'#ffffff'});const link=document.createElement('a');link.download=`שיבוץ-הדס-${dateISO(state.weekStart)}.png`;link.href=canvas.toDataURL('image/png');link.click();}

async function showSuggestions(date,classId){state.suggestionsContext={date,classId,start:'07:30',end:'15:30',role:'staff'};$('#suggestionsList').innerHTML='<div class="empty-state">מחפש עובדות פנויות…</div>';$('#suggestionsDialog').showModal();try{const result=await apiFetch(`/api/suggestions?date=${date}&class_id=${classId}&start_time=07:30&end_time=15:30&shift_role=staff`);$('#suggestionsList').innerHTML=result.candidates.length?result.candidates.map(c=>`<article class="suggestion-card"><div class="card-heading"><div><h3>${escapeHtml(c.full_name)}</h3><p class="muted">${escapeHtml(c.job_title)}</p></div><span class="score-chip">ציון ${c.score}</span></div><ul class="reason-list">${c.reasons.map(r=>`<li>${escapeHtml(r)}</li>`).join('')}</ul><button class="primary-btn" data-action="use-suggestion" data-id="${c.employee_id}" data-role="${c.suggested_role}">שיבוץ העובדת</button></article>`).join(''):'<div class="empty-state">לא נמצאה מחליפה זמינה.</div>';}catch(error){$('#suggestionsList').innerHTML=`<div class="empty-state">${escapeHtml(error.message)}</div>`;}}
async function handleSuggestionClick(event){const btn=event.target.closest('[data-action="use-suggestion"]');if(!btn)return;const c=state.suggestionsContext;try{await apiFetch('/api/shifts',{method:'POST',body:{shift_date:c.date,class_id:c.classId,employee_id:btn.dataset.id,start_time:c.start,end_time:c.end,shift_role:btn.dataset.role,status:'draft',public_note:'שובצה כהחלפה'}});$('#suggestionsDialog').close();await refreshAll();showToast('המחליפה שובצה','success');}catch(error){showToast(error.message,'error');}}

function renderEmployees(){const rows=state.employees.map(e=>`<tr><td><strong>${escapeHtml(e.full_name)}</strong><small>${escapeHtml(e.job_title)}</small></td><td>${escapeHtml(e.phone||'')}</td><td>${escapeHtml(classById(e.primary_class_id)?.name||'ללא')}</td><td>${ROLE_LABELS[e.role]||e.role}</td><td>${e.weekly_hours??'—'}</td><td><span class="status-chip ${e.active?'ok':'error'}">${e.active?'פעילה':'לא פעילה'}</span></td><td><div class="card-actions"><button class="ghost-btn small-btn" data-action="edit-employee" data-id="${e.id}">עריכה</button><button class="secondary-btn small-btn" data-action="reset-password" data-id="${e.id}">איפוס סיסמה</button><button class="${e.active?'danger-btn':'primary-btn'} small-btn" data-action="${e.active?'deactivate-employee':'activate-employee'}" data-id="${e.id}">${e.active?'השבתה':'הפעלה'}</button></div></td></tr>`).join('');$('#employeesList').innerHTML=`<div class="table-scroll"><table class="data-table"><thead><tr><th>עובדת</th><th>טלפון</th><th>כיתה</th><th>הרשאה</th><th>שעות</th><th>מצב</th><th>פעולות</th></tr></thead><tbody>${rows}</tbody></table></div>`;}
function renderConstraintFields(employeeId){$('#constraintsFields').innerHTML=state.classes.filter(c=>c.active).map(c=>{const item=state.constraints.find(x=>x.employee_id===employeeId&&x.class_id===c.id)||{};return `<div class="constraint-row" data-class-id="${c.id}"><strong>${escapeHtml(c.name)}</strong><select class="constraint-type"><option value="">ללא</option><option value="preferred" ${item.constraint_type==='preferred'?'selected':''}>עדיפות</option><option value="avoid" ${item.constraint_type==='avoid'?'selected':''}>עדיף להימנע</option><option value="forbidden" ${item.constraint_type==='forbidden'?'selected':''}>אסור</option></select><input class="constraint-from" type="date" value="${item.valid_from||''}" title="מתאריך"/><input class="constraint-to" type="date" value="${item.valid_to||''}" title="עד תאריך"/><input class="constraint-reason" value="${escapeHtml(item.reason||'')}" placeholder="סיבה"/></div>`;}).join('');}
function collectConstraints(){return $$('.constraint-row').map(row=>({class_id:row.dataset.classId,constraint_type:$('.constraint-type',row).value,valid_from:$('.constraint-from',row).value||null,valid_to:$('.constraint-to',row).value||null,reason:$('.constraint-reason',row).value||null})).filter(x=>x.constraint_type);}
function openEmployeeDialog(id){const form=$('#employeeForm');form.reset();const e=id?employeeById(id):null;form.elements.id.value=e?.id||'';form.elements.full_name.value=e?.full_name||'';form.elements.phone.value=e?.phone||'';form.elements.job_title.value=e?.job_title||'אשת צוות';form.elements.role.value=e?.role||'employee';form.elements.primary_class_id.value=e?.primary_class_id||'';form.elements.can_lead.value=String(Boolean(e?.can_lead));form.elements.weekly_hours.value=e?.weekly_hours??'';form.elements.employment_percent.value=e?.employment_percent??'';form.elements.fixed_day_off.value=e?.fixed_day_off??'';form.elements.default_start.value=trimTime(e?.default_start)||'07:30';form.elements.default_end.value=trimTime(e?.default_end)||'15:30';form.elements.admin_notes.value=e?.admin_notes||'';renderConstraintFields(e?.id);$('#employeeDialog').showModal();}
async function saveEmployee(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[value="default"]'),data=formObject(form);data.can_lead=data.can_lead==='true';data.constraints=collectConstraints();setBusy(button,true);try{await apiFetch('/api/employees',{method:data.id?'PATCH':'POST',body:data});$('#employeeDialog').close();await refreshAll();showToast('כרטיס העובדת נשמר','success');}catch(error){showToast(error.message,'error');}finally{setBusy(button,false);}}
async function handleEmployeeClick(event){const btn=event.target.closest('[data-action]');if(!btn)return;const id=btn.dataset.id;try{if(btn.dataset.action==='edit-employee')return openEmployeeDialog(id);if(btn.dataset.action==='reset-password'){if(!confirm('לאפס את הסיסמה ל-hadas ולנתק את העובדת?'))return;await apiFetch('/api/employees',{method:'PATCH',body:{id,reset_password:true}});}if(btn.dataset.action==='deactivate-employee'){if(!confirm('להשבית את העובדת? ההיסטוריה תישמר.'))return;await apiFetch('/api/employees',{method:'DELETE',body:{id}});}if(btn.dataset.action==='activate-employee')await apiFetch('/api/employees',{method:'PATCH',body:{id,active:true}});await refreshAll();showToast('העובדת עודכנה','success');}catch(error){showToast(error.message,'error');}}

function openRequestDialog(){const form=$('#requestForm');form.reset();form.elements.request_date.value=dateISO(new Date());updateRequestShiftOptions();updateRequestFields();$('#requestDialog').showModal();}
function updateRequestFields(){const form=$('#requestForm'),type=form.elements.request_type.value,needsShift=['late_start','early_finish','swap'].includes(type);$$('.request-start').forEach(e=>e.classList.toggle('hidden',type!=='late_start'));$$('.request-end').forEach(e=>e.classList.toggle('hidden',type!=='early_finish'));$$('.shift-choice-field').forEach(e=>e.classList.toggle('hidden',!needsShift));$$('.swap-field').forEach(e=>e.classList.toggle('hidden',type!=='swap'));form.elements.shift_id.required=needsShift;form.elements.target_employee_id.required=type==='swap';form.elements.target_shift_id.required=type==='swap';form.elements.requested_start.required=type==='late_start';form.elements.requested_end.required=type==='early_finish';}
function updateRequestShiftOptions(){const mine=state.shifts.filter(s=>s.employee_id===state.profile.id);$('#requestForm [name="shift_id"]').innerHTML=`<option value="">בחרי שיבוץ</option>${mine.map(s=>`<option value="${s.id}">${formatDate(s.shift_date)} · ${classById(s.class_id)?.name||''} · ${trimTime(s.start_time)}–${trimTime(s.end_time)}</option>`).join('')}`;populateTargetShifts();}
function syncRequestDateFromShift(){const form=$('#requestForm'),shift=state.shifts.find(s=>s.id===form.elements.shift_id.value);if(shift)form.elements.request_date.value=shift.shift_date;}
function populateTargetShifts(){const id=$('#requestForm [name="target_employee_id"]').value;$('#requestForm [name="target_shift_id"]').innerHTML=`<option value="">בחרי שיבוץ</option>${state.shifts.filter(s=>s.employee_id===id).map(s=>`<option value="${s.id}">${formatDate(s.shift_date)} · ${classById(s.class_id)?.name||''} · ${trimTime(s.start_time)}–${trimTime(s.end_time)}</option>`).join('')}`;}
async function saveRequest(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[value="default"]'),data=formObject(form);setBusy(button,true,'שולחת…');try{await apiFetch('/api/requests',{method:'POST',body:{action:'create',...data}});$('#requestDialog').close();await refreshAll();showToast('הבקשה נשלחה','success');}catch(error){showToast(error.message,'error');}finally{setBusy(button,false);}}
function renderRequests(){$('#requestsList').innerHTML=state.requests.length?state.requests.map(r=>{const requester=employeeById(r.requester_id),target=employeeById(r.target_employee_id);return `<article class="request-card"><div class="card-heading"><div><h3>${REQUEST_LABELS[r.request_type]}</h3><p class="muted">${escapeHtml(requester?.full_name||'')} · ${formatDate(r.request_date)}</p></div><span class="status-chip ${r.status==='rejected'?'error':r.status==='applied'?'ok':'warn'}">${REQUEST_STATUS_LABELS[r.status]}</span></div><div class="meta-grid"><div class="meta-item"><small>פירוט</small>${escapeHtml(r.reason||'ללא')}</div><div class="meta-item"><small>החלפה עם</small>${escapeHtml(target?.full_name||'לא רלוונטי')}${r.request_type==='swap'?` · ${r.target_approved?'אישרה':'טרם אישרה'}`:''}</div></div>${r.manager_note?`<div class="manager-note"><strong>הערת מנהלת:</strong> ${escapeHtml(r.manager_note)}</div>`:''}<div class="card-actions">${r.request_type==='swap'&&r.target_employee_id===state.profile.id&&!r.target_approved&&r.status==='pending'?`<button class="secondary-btn" data-action="target_accept" data-id="${r.id}">אני מסכימה</button>`:''}${r.requester_id===state.profile.id&&r.status==='pending'?`<button class="ghost-btn" data-action="cancel" data-id="${r.id}">ביטול</button>`:''}${isManager()&&r.status==='pending'?`<button class="primary-btn" data-action="approve" data-id="${r.id}">אישור</button><button class="danger-btn" data-action="reject" data-id="${r.id}">דחייה</button>`:''}${isManager()&&r.status==='approved'?`<button class="primary-btn" data-action="apply" data-id="${r.id}">הזרמה לשיבוץ</button>`:''}</div></article>`;}).join(''):'<div class="empty-state">אין בקשות.</div>';}
async function handleRequestClick(event){const btn=event.target.closest('[data-action]');if(!btn)return;let body={id:btn.dataset.id,action:btn.dataset.action};if(btn.dataset.action==='approve'||btn.dataset.action==='reject'){body={...body,action:'decide',status:btn.dataset.action==='approve'?'approved':'rejected',manager_note:prompt('הערה לעובדת (אפשר להשאיר ריק):')||''};}if(btn.dataset.action==='apply'&&!confirm('להזרים את הבקשה לשיבוץ בפועל?'))return;try{await apiFetch('/api/requests',{method:'POST',body});await refreshAll();showToast('הבקשה עודכנה','success');}catch(error){showToast(error.message,'error');}}

function renderAttendance(){const shifts=state.shifts.filter(s=>s.shift_date===state.attendanceDate&&(isManager()||s.employee_id===state.profile.id));$('#attendanceList').innerHTML=shifts.length?shifts.map(s=>{const row=state.attendance.find(a=>a.shift_id===s.id);return `<article class="attendance-card" data-shift-id="${s.id}"><div class="card-heading"><div><h3>${escapeHtml(employeeById(s.employee_id)?.full_name||'')}</h3><p class="muted">${escapeHtml(classById(s.class_id)?.name||'')} · ${trimTime(s.start_time)}–${trimTime(s.end_time)}</p></div><span class="role-chip">${SHIFT_ROLE_LABELS[s.shift_role]}</span></div>${isManager()?`<div class="form-grid"><label>מצב<select class="attendance-status">${Object.entries(ATTENDANCE_LABELS).map(([v,l])=>`<option value="${v}" ${(row?.status||'scheduled')===v?'selected':''}>${l}</option>`).join('')}</select></label><label>התחלה בפועל<input class="attendance-start" type="time" value="${trimTime(row?.actual_start)||trimTime(s.start_time)}"/></label><label>סיום בפועל<input class="attendance-end" type="time" value="${trimTime(row?.actual_end)||trimTime(s.end_time)}"/></label><label>הערה<input class="attendance-note" value="${escapeHtml(row?.note||'')}"/></label></div><button class="primary-btn" data-action="save-attendance">שמירה</button>`:`<div class="meta-grid"><div class="meta-item"><small>מצב</small>${ATTENDANCE_LABELS[row?.status||'scheduled']}</div><div class="meta-item"><small>בפועל</small>${trimTime(row?.actual_start)||'—'}–${trimTime(row?.actual_end)||'—'}</div></div>`}</article>`;}).join(''):`<div class="empty-state">אין שיבוצים בתאריך ${formatDate(state.attendanceDate)}.</div>`;}
async function handleAttendanceClick(event){const btn=event.target.closest('[data-action="save-attendance"]');if(!btn)return;const card=btn.closest('[data-shift-id]');try{await apiFetch('/api/attendance',{method:'POST',body:{shift_id:card.dataset.shiftId,status:$('.attendance-status',card).value,actual_start:$('.attendance-start',card).value,actual_end:$('.attendance-end',card).value,note:$('.attendance-note',card).value}});await refreshAll();showToast('הנוכחות נשמרה','success');}catch(error){showToast(error.message,'error');}}

function openDialogForm(dialogSelector,formSelector){const form=$(formSelector);form.reset();$(dialogSelector).showModal();}
function renderAnnouncements(){$('#announcementsList').innerHTML=state.announcements.length?state.announcements.map(a=>{const read=state.announcementReads.some(r=>r.announcement_id===a.id&&r.employee_id===state.profile.id);const readCount=state.announcementReads.filter(r=>r.announcement_id===a.id).length;return `<article class="announcement-card ${a.announcement_type}"><div class="card-heading"><div><h3>${escapeHtml(a.title)}${!read?'<span class="unread-dot"></span>':''}</h3><p class="muted">${formatDate(a.published_at,{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}</p></div><span class="status-chip ${a.announcement_type==='urgent'?'error':a.announcement_type==='important'?'warn':'ok'}">${a.announcement_type==='urgent'?'דחוף':a.announcement_type==='important'?'חשוב':'מידע'}</span></div><p>${escapeHtml(a.body).replaceAll('\n','<br>')}</p><div class="card-actions">${!read?`<button class="primary-btn" data-action="read" data-id="${a.id}">קראתי</button>`:''}${isManager()?`<span class="small-note">נקראה על ידי ${readCount}</span><button class="danger-btn" data-action="delete" data-id="${a.id}">הסרה</button>`:''}</div></article>`;}).join(''):'<div class="empty-state">אין הודעות.</div>';}
async function saveAnnouncement(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[value="default"]'),data=formObject(form);data.expires_at=toIsoDateTime(data.expires_at);setBusy(button,true);try{await apiFetch('/api/announcements',{method:'POST',body:data});$('#announcementDialog').close();await refreshAll();showToast('ההודעה פורסמה','success');}catch(error){showToast(error.message,'error');}finally{setBusy(button,false);}}
async function handleAnnouncementClick(event){const btn=event.target.closest('[data-action]');if(!btn)return;try{if(btn.dataset.action==='delete'&&!confirm('להסיר את ההודעה?'))return;await apiFetch('/api/announcements',{method:btn.dataset.action==='delete'?'DELETE':'POST',body:{action:btn.dataset.action,id:btn.dataset.id}});await refreshAll();}catch(error){showToast(error.message,'error');}}

function populateTaskTarget(){const form=$('#taskForm'),type=form.elements.target_type.value;form.elements.target_id.disabled=type==='all';form.elements.target_id.innerHTML=type==='class'?`<option value="">בחרי כיתה</option>${state.classes.filter(c=>c.active).map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('')}`:type==='employee'?`<option value="">בחרי עובדת</option>${state.employees.filter(e=>e.active).map(e=>`<option value="${e.id}">${escapeHtml(e.full_name)}</option>`).join('')}`:'<option value="">כל העובדות</option>';}
function openTaskDialog(){const form=$('#taskForm');form.reset();populateTaskTarget();$('#taskDialog').showModal();}
function renderTasks(){$('#tasksList').innerHTML=state.tasks.filter(t=>t.active).length?state.tasks.filter(t=>t.active).map(t=>{const assignments=state.taskAssignees.filter(a=>a.task_id===t.id),mine=assignments.find(a=>a.employee_id===state.profile.id),done=assignments.filter(a=>a.status==='done').length,percent=assignments.length?Math.round(done/assignments.length*100):0;return `<article class="task-card"><div class="card-heading"><div><h3>${escapeHtml(t.title)}</h3><p class="muted">עדיפות ${PRIORITY_LABELS[t.priority]}${t.due_at?` · עד ${formatDate(t.due_at,{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'})}`:''}</p></div><span class="status-chip ${t.priority==='urgent'?'error':t.priority==='important'?'warn':'ok'}">${mine?.status==='done'?'בוצע':'פתוח'}</span></div><p>${escapeHtml(t.description||'ללא פירוט')}</p>${isManager()?`<div class="small-note">${done} מתוך ${assignments.length} ביצעו</div><div class="progress-track"><span style="width:${percent}%"></span></div>`:''}<div class="card-actions">${mine?`<button class="${mine.status==='done'?'ghost-btn':'primary-btn'}" data-action="${mine.status==='done'?'reopen':'complete'}" data-id="${t.id}">${mine.status==='done'?'פתיחה מחדש':'סימון בוצע'}</button>`:''}${isManager()?`<button class="danger-btn" data-action="delete" data-id="${t.id}">הסרה</button>`:''}</div></article>`;}).join(''):'<div class="empty-state">אין משימות.</div>';}
async function saveTask(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[value="default"]'),data=formObject(form);data.due_at=toIsoDateTime(data.due_at);setBusy(button,true);try{await apiFetch('/api/tasks',{method:'POST',body:data});$('#taskDialog').close();await refreshAll();showToast('המשימה נוצרה','success');}catch(error){showToast(error.message,'error');}finally{setBusy(button,false);}}
async function handleTaskClick(event){const btn=event.target.closest('[data-action]');if(!btn)return;if(btn.dataset.action==='delete'&&!confirm('להסיר את המשימה?'))return;try{await apiFetch('/api/tasks',{method:btn.dataset.action==='delete'?'DELETE':'POST',body:{action:btn.dataset.action,id:btn.dataset.id}});await refreshAll();}catch(error){showToast(error.message,'error');}}

function openCalendarDialog(){const form=$('#calendarForm');form.reset();form.elements.event_date.value=dateISO(new Date());$('#calendarDialog').showModal();}
function renderCalendar(){$('#calendarList').innerHTML=state.calendarEvents.length?state.calendarEvents.map(e=>`<article class="timeline-item"><div class="timeline-date">${formatDate(e.event_date,{weekday:'short',day:'numeric',month:'short'})}</div><div class="timeline-content"><h3>${escapeHtml(e.title)}</h3><p>${EVENT_LABELS[e.event_type]}${e.start_time?` · ${trimTime(e.start_time)}${e.end_time?`–${trimTime(e.end_time)}`:''}`:''}${e.class_id?` · ${escapeHtml(classById(e.class_id)?.name||'')}`:''}</p>${e.description?`<p>${escapeHtml(e.description)}</p>`:''}</div>${isManager()?`<div class="card-actions"><button class="danger-btn small-btn" data-action="delete" data-id="${e.id}">מחיקה</button></div>`:''}</article>`).join(''):'<div class="empty-state">אין אירועים בטווח הקרוב.</div>';}
async function saveCalendarEvent(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[value="default"]'),data=formObject(form);setBusy(button,true);try{await apiFetch('/api/calendar',{method:'POST',body:data});$('#calendarDialog').close();await refreshAll();showToast('האירוע נשמר','success');}catch(error){showToast(error.message,'error');}finally{setBusy(button,false);}}
async function handleCalendarClick(event){const btn=event.target.closest('[data-action="delete"]');if(!btn||!confirm('למחוק את האירוע?'))return;try{await apiFetch('/api/calendar',{method:'DELETE',body:{id:btn.dataset.id}});await refreshAll();}catch(error){showToast(error.message,'error');}}

function fileSize(size){const n=Number(size||0);if(n<1024)return`${n} B`;if(n<1024*1024)return`${(n/1024).toFixed(1)} KB`;return`${(n/1024/1024).toFixed(1)} MB`;}
function renderDocuments(){$('#documentsList').innerHTML=state.documents.length?state.documents.map(d=>`<article class="document-card"><div class="card-heading"><div><h3>${escapeHtml(d.title)}</h3><p class="muted">${escapeHtml(d.file_name)} · ${fileSize(d.size_bytes)}</p></div><span class="role-chip">מסמך</span></div>${d.description?`<p>${escapeHtml(d.description)}</p>`:''}<div class="card-actions"><button class="primary-btn" data-action="download" data-id="${d.id}">הורדה</button>${isManager()?`<button class="danger-btn" data-action="delete" data-id="${d.id}">הסרה</button>`:''}</div></article>`).join(''):'<div class="empty-state">אין מסמכים.</div>';}
async function saveDocument(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[value="default"]'),data=formObject(form),file=form.elements.file.files[0];if(!file)return;if(!state.storageClient)return showToast('רכיב העלאת הקבצים לא נטען. רעננו את הדף ונסו שוב.','error');setBusy(button,true,'מעלה…');try{const prepared=await apiFetch('/api/documents',{method:'POST',body:{action:'prepare',file_name:file.name,mime_type:file.type,size_bytes:file.size}});const upload=await state.storageClient.storage.from('hadas-documents').uploadToSignedUrl(prepared.path,prepared.token,file,{contentType:file.type});if(upload.error)throw upload.error;await apiFetch('/api/documents',{method:'POST',body:{action:'confirm',title:data.title,description:data.description,visibility:data.visibility,class_id:data.class_id||null,file_name:file.name,storage_path:prepared.path,mime_type:file.type,size_bytes:file.size}});$('#documentDialog').close();await refreshAll();showToast('המסמך הועלה','success');}catch(error){showToast(error.message,'error');}finally{setBusy(button,false);}}
async function handleDocumentClick(event){const btn=event.target.closest('[data-action]');if(!btn)return;try{if(btn.dataset.action==='download'){const data=await apiFetch(`/api/documents?id=${btn.dataset.id}`);window.location.href=data.url;}else{if(!confirm('להסיר את המסמך?'))return;await apiFetch('/api/documents',{method:'DELETE',body:{id:btn.dataset.id}});await refreshAll();}}catch(error){showToast(error.message,'error');}}

function openSettings(){const form=$('#settingsForm');for(const name of ['opening_time','closing_time'])form.elements[name].value=trimTime(state.settings[name]);for(const name of ['required_staff','closing_required_staff','closing_window_minutes','validation_slot_minutes'])form.elements[name].value=state.settings[name];$('#settingsDialog').showModal();}
async function saveSettings(event){event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[value="default"]'),data=formObject(form);for(const name of ['required_staff','closing_required_staff','closing_window_minutes','validation_slot_minutes'])data[name]=Number(data[name]);setBusy(button,true);try{await apiFetch('/api/settings',{method:'PATCH',body:data});$('#settingsDialog').close();await refreshAll();showToast('ההגדרות נשמרו','success');}catch(error){showToast(error.message,'error');}finally{setBusy(button,false);}}

init();
