/* מערכת ניהול שיבוצים מעון הדס — bootstrap יציב לגרסה 0.34.0 */
(() => {
  const VERSION='0.34.0';
  const chain=[['/patch-v026.js?v=0321','v026'],['/patch-v033.js?v=0333','v033'],['/patch-v0331-hotfix.js?v=0331hf2','v0331-hotfix'],['/patch-v034.js?v=0340','v034'],['/patch-v0341.js?v=0341a','v0341'],['/patch-v0342.js?v=0342a','v0342'],['/patch-v0343.js?v=0343a','v0343']];
  let releaseGate;let released=false;const ready=new Promise(r=>releaseGate=r);const base=typeof apiFetch==='function'?apiFetch:null;
  function forceVersion(){window.__HADAS_RELEASE_VERSION=VERSION;const b=document.querySelector('#appVersionBadge');if(b){b.textContent=`v${VERSION}`;b.title=`גרסת מערכת ${VERSION}`;}const l=document.querySelector('#loginVersion');if(l)l.textContent=`גרסה ${VERSION}`;document.documentElement.dataset.hadasVersion=VERSION;}
  function release(){if(released)return;released=true;window.__hadasCurrentBootstrapReady=true;releaseGate();window.dispatchEvent(new CustomEvent('hadas:bootstrap-ready',{detail:{version:VERSION}}));}
  if(base)apiFetch=async function(...args){await ready;return base(...args);};
  function shellVisible(){const s=document.querySelector('#appShell');return Boolean(s&&!s.classList.contains('hidden'));}
  function closeUnsafeTour(){const d=document.querySelector('#v031TourDialog');if(!d?.open)return;const logged=typeof state!=='undefined'&&Boolean(state?.profile);if(!logged||!shellVisible()){try{d.close();}catch{};d.dataset.started='';document.querySelectorAll('.v031-tour-highlight').forEach(x=>x.classList.remove('v031-tour-highlight'));}}
  function installSafety(){const observer=new MutationObserver(closeUnsafeTour);observer.observe(document.body,{childList:true,subtree:true,attributes:true});if(typeof setScreen==='function'&&!window.__hadasSafeSetScreenInstalled){const old=setScreen;setScreen=function(id){const r=old(id);if(id!=='appShell')queueMicrotask(closeUnsafeTour);return r;};window.__hadasSafeSetScreenInstalled=true;}}
  function load(src,marker){return new Promise((resolve,reject)=>{const existing=document.querySelector(`script[data-hadas-bootstrap="${marker}"]`);if(existing){if(existing.dataset.loaded==='true')return resolve();existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return;}const s=document.createElement('script');s.src=src;s.async=false;s.dataset.hadasBootstrap=marker;s.addEventListener('load',()=>{s.dataset.loaded='true';resolve();},{once:true});s.addEventListener('error',()=>reject(new Error(`לא ניתן לטעון ${src}`)),{once:true});document.head.append(s);});}
  async function boot(){if(window.__hadasCurrentBootstrapStarted)return;window.__hadasCurrentBootstrapStarted=true;forceVersion();installSafety();try{for(const [src,marker] of chain){await load(src,marker);if(marker==='v033'&&window.__hadasV033BootstrapPromise)await window.__hadasV033BootstrapPromise;if(marker==='v034'&&window.__hadasV034BootstrapPromise)await window.__hadasV034BootstrapPromise;if(marker==='v0341'&&window.__hadasV0341BootstrapPromise)await window.__hadasV0341BootstrapPromise;if(marker==='v0342'&&window.__hadasV0342BootstrapPromise)await window.__hadasV0342BootstrapPromise;}forceVersion();}catch(e){console.error('Hadas bootstrap failed',e);const t=document.querySelector('#toast');if(t){t.textContent='טעינת עדכון המערכת נכשלה. מומלץ לרענן.';t.classList.remove('hidden');}}finally{release();}}
  forceVersion();boot();
})();
