/* מעון הדס — v0.37.0: הצעות תיקון חכמות + תיקוני מובייל */
(() => {
  if (window.__hadasV037Installed) return;
  window.__hadasV037Installed = true;
  const VERSION='0.37.0', MQ='(max-width:760px)';
  const COVER=new Set(['understaffed','missing_leader']);
  const REPLACE=new Set(['approved_absence','fixed_day_off','forbidden_class','teacher_fixed_class','overlap','max_weekly_hours','max_weekly_days']);
  let validationObserver, toolsObserver, toolsState=null, toolsClick=false, proposal=null;
  const dateOf=x=>String(x?.date||x?.shift_date||'');
  const classOf=x=>x?.classId||x?.class_id||null;
  const employeeOf=x=>x?.employeeId||x?.employee_id||null;
  const originals=g=>Array.isArray(g?._v032Originals)&&g._v032Originals.length?g._v032Originals:[g];
  const short=v=>v?String(v).slice(0,5):'';
  const mins=v=>timeToMinutes(short(v));
  const mobile=()=>matchMedia(MQ).matches;

  function pinVersion(){
    window.__HADAS_RELEASE_VERSION=VERSION; document.documentElement.dataset.hadasVersion=VERSION;
    const b=document.querySelector('#appVersionBadge'),l=document.querySelector('#loginVersion');
    if(b){b.textContent=`v${VERSION}`;b.title=`גרסת מערכת ${VERSION}`;} if(l)l.textContent=`גרסה ${VERSION}`;
  }

  function fixTools(){
    const d=document.querySelector('.schedule-tools-menu'); if(!d)return;
    if(!d.dataset.v037){
      d.dataset.v037='1'; const s=d.querySelector('summary');
      s?.addEventListener('click',()=>{toolsClick=true;setTimeout(()=>{toolsState=!!d.open;toolsClick=false;},0);});
      toolsObserver?.disconnect?.(); toolsObserver=new MutationObserver(()=>{
        if(mobile()&&!toolsClick&&d.open!==!!toolsState)queueMicrotask(()=>{d.open=!!toolsState;});
      }); toolsObserver.observe(d,{attributes:true,attributeFilter:['open']});
    }
    if(mobile()){if(toolsState===null)toolsState=false;d.open=!!toolsState;}
  }

  function addStyles(){if(document.querySelector('#v037Style'))return;const s=document.createElement('style');s.id='v037Style';s.textContent=`
    .v037-suggest{background:#f1efff!important;border:1px solid #d8d6f8!important;color:#554fc4!important;font-weight:900!important}.v037-suggest:before{content:'✦ '}
    .v037-focus{outline:3px solid #e35b66!important;outline-offset:3px!important;border-radius:14px!important;box-shadow:0 0 0 7px #e35b6618!important}
    .v037-box{display:grid;gap:12px;padding:15px;border:1px solid #dedff0;border-radius:17px;background:#fafaff}.v037-box h4,.v037-box p{margin:0}.v037-box p,.v037-box small{color:#6f7486;line-height:1.5}
    .v037-change{padding:11px 13px;background:#fff;border:1px solid #e5e6ef;border-radius:13px}.v037-tags{display:flex;flex-wrap:wrap;gap:6px}.v037-tags span{padding:5px 8px;border-radius:999px;background:#eff2f7;font-size:.78rem;font-weight:800}
    .v037-loading{padding:18px;text-align:center;color:#666c80}.v037-actions{display:flex;gap:8px}.v037-actions button{flex:1}
    @media(max-width:760px){.v032-validation-actions{display:grid!important;grid-template-columns:1fr 1fr;gap:8px!important}.v032-validation-actions .v037-suggest{grid-column:1/-1;min-height:44px}.v037-actions{display:grid}.v037-actions button{width:100%}}
  `;document.head.append(s);}

  function ensureDialog(){let d=document.querySelector('#v037Dialog');if(d)return d;d=document.createElement('dialog');d.id='v037Dialog';d.className='modal';d.innerHTML=`<div class="modal-card"><div class="modal-heading"><div><p class="eyebrow">בדיקות תקינות</p><h3>הצעת תיקון</h3></div><button class="icon-btn" type="button" data-v037-close>×</button></div><div id="v037Body"></div><div id="v037Actions" class="modal-actions v037-actions"></div></div>`;document.body.append(d);return d;}

  function decorate(){const p=document.querySelector('#scheduleWarnings');if(!p||!isManager())return;p.querySelectorAll('.v032-validation-card.error').forEach(c=>{const a=c.querySelector('.v032-validation-actions');if(!a||a.querySelector('[data-v037-suggest]'))return;const src=a.querySelector('[data-v032-focus]')||a.querySelector('[data-v032-group]');const id=src?.dataset.v032Focus||src?.dataset.v032Group;if(!id)return;const b=document.createElement('button');b.type='button';b.className='ghost-btn v037-suggest';b.dataset.v037Suggest=id;b.textContent='הצע פתרון';a.prepend(b);});}

  function contextFor(g){let date=dateOf(g),classId=classOf(g);const employeeId=employeeOf(g);if((!date||!classId)&&employeeId){const r=(state.shifts||[]).filter(x=>x.employee_id===employeeId&&(!date||x.shift_date===date)).sort((a,b)=>`${a.shift_date}${a.start_time}`.localeCompare(`${b.shift_date}${b.start_time}`))[0];if(r){date||=r.shift_date;classId||=r.class_id;}}return{date,classId,employeeId};}

  function focusIssue(g){const {date,classId,employeeId}=contextFor(g);state.scheduleMode='week';storageSet('localStorage','hadas-schedule-mode','week');if(mobile()){const i=currentWeekDates().findIndex(x=>dateISO(x)===date);if(i>=0)state.expandedWeekDay=i;}renderSchedule();requestAnimationFrame(()=>requestAnimationFrame(()=>{let t=null;if(mobile()){const i=currentWeekDates().findIndex(x=>dateISO(x)===date),day=document.querySelector(`.mobile-week-day[data-day-index="${i}"]`);if(day){day.open=true;const ci=visibleScheduleClasses().findIndex(x=>String(x.id)===String(classId));t=ci>=0?day.querySelectorAll('.mobile-week-class')[ci]:day;}}else{if(employeeId){const sh=(state.shifts||[]).find(x=>x.employee_id===employeeId&&(!date||x.shift_date===date)&&(!classId||String(x.class_id)===String(classId)));if(sh)t=document.querySelector(`#scheduleExport .shift-item[data-shift-id="${sh.id}"]`);}if(!t&&classId){const ci=visibleScheduleClasses().findIndex(x=>String(x.id)===String(classId)),di=currentWeekDates().findIndex(x=>dateISO(x)===date);if(ci>=0&&di>=0)t=document.querySelectorAll('.schedule-desktop-week tbody tr')[ci]?.querySelectorAll('td')[di+1];}}if(!t)return showToast('הבעיה מוצגת בתצוגת השבוע.');t.classList.add('v037-focus');t.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});setTimeout(()=>t.classList.remove('v037-focus'),4000);}));}

  function ranges(g){return originals(g).filter(x=>COVER.has(x?.code)).map(x=>({code:x.code,start:short(x.time||x.start_time),end:short(x.end_time)})).filter(x=>x.start&&x.end&&mins(x.end)>mins(x.start)).sort((a,b)=>mins(a.start)-mins(b.start));}
  function maxSafe(date,classId,start,end){const max=Number(state.settings?.max_daily_staff);if(!Number.isInteger(max)||max<=0)return true;for(let m=mins(start);m<mins(end);m+=15){const a=minutesLabel(m),b=minutesLabel(Math.min(mins(end),m+15));const n=new Set((state.shifts||[]).filter(x=>x.shift_date===date&&x.class_id===classId&&overlaps(x.start_time,x.end_time,a,b)).map(x=>x.employee_id)).size;if(n+1>max)return false;}return true;}
  const candidateRank=c=>Number(c?.score||0)+(c?.recommended?22:0)+(c?.candidate_type==='direct'?8:0)-((c?.cautions||[]).length*2);
  function best(result){return [...(result?.candidates||[])].sort((a,b)=>candidateRank(b)-candidateRank(a)).find(c=>(c.recommended&&Number(c.score)>=62)||Number(c.score)>=76)||null;}

  async function coverageProposal(g){const {date,classId}=contextFor(g),rs=ranges(g);if(!date||!classId||!rs.length)return{unsupported:true,group:g,reason:'חסרים פרטים כדי לחשב תיקון אוטומטי בטוח.'};const start=rs[0].start,end=rs.reduce((v,x)=>mins(x.end)>mins(v)?x.end:v,rs[0].end);if(!maxSafe(date,classId,start,end))return{unsupported:true,group:g,reason:'שיבוץ רציף לטווח הזה ייצור עודף כוח אדם בחלק מהיום, ולכן לא אציע שינוי אוטומטי.'};const role=rs.some(x=>x.code==='missing_leader')?'teacher':'staff';const r=await fetchMatchingCandidates({date,classId,start,end,role,shiftId:null},{force:true,timeout:10000}),c=best(r);if(!c)return{unsupported:true,group:g,reason:'לא נמצא כרגע עובד שעובר את כל בדיקות הזמינות והתקינה ברמת התאמה טובה מספיק.'};const cn=classById(classId)?.name||'הכיתה';return{type:'suggest',group:g,candidate:c,date,classId,start,end,role,title:`שיבוץ ${c.full_name} ב${cn}`,change:`${c.full_name} · ${start}–${end}`,detail:rs.length>1?`ההצעה מכסה את ${rs.length} טווחי החוסר בשינוי אחד, אמקום ליצור כמה שיבוצים קצרים.`:'השיבוץ מכסה בדיוק את טווח החוסר.',reasons:[...(c.reasons||[]).slice(0,3),c.candidate_type==='direct'?'ללא פגיעה בכיתה אחרת':`העברה בטוחה מ${c.from_class_name||'כיתה אחרת'}`],score:c.score};}

  function issueShifts(g){const {date,classId,employeeId}=contextFor(g);let a=[...(state.shifts||[])];if(date)a=a.filter(x=>x.shift_date===date);if(classId)a=a.filter(x=>String(x.class_id)===String(classId));if(employeeId)a=a.filter(x=>x.employee_id===employeeId);return a;}
  async function replacementProposal(g){const a=issueShifts(g);if(!a.length)return{unsupported:true,group:g,reason:'לא נמצא שיבוץ יחיד שאפשר לתנות בבטחה.'};const opts=await Promise.all(a.slice(0,3).map(async sh=>{const r=await fetchMatchingCandidates({date:sh.shift_date,classId:sh.class_id,start:short(sh.start_time),end:short(sh.end_time),role:sh.shift_role||'staff',shiftId:sh.id},{force:true,timeout:10000});const c=best(r);return c?{sh,c,v:candidateRank(c)}:null;}));const o=opts.filter(Boolean).sort((x,y)=>y.v-x.v)[0];if(!o)return{unsupported:true,group:g,reason:'לא נמצא מחליף שעובר את כל כללי השיבוץ ברמת התאמה טובה מספיק.'};const old=employeeById(o.sh.employee_id)?.full_name||'העובד/ת',cn=classById(o.sh.class_id)?.name||'הכיתה';return{type:'suggest',group:g,candidate:o.c,date:o.sh.shift_date,classId:o.sh.class_id,start:short(o.sh.start_time),end:short(o.sh.end_time),role:o.sh.shift_role||'staff',shiftId:o.sh.id,old,title:`החלפת ${old} ב${o.c.full_name}`,change:`${cn} · ${short(o.sh.start_time)}–${short(o.sh.end_time)}`,detail:'ההחלפה שומרת את שעות הכיתה ומסירה את השיבוץ שיצר את החריגה.',reasons:(o.c.reasons||[]).slice(0,3),score:o.c.score};}
  function hoursProposal(g){const sh=issueShifts(g)[0];if(!sh)return{unsupported:true,group:g,reason:'לא נמצא השיבוץ שיצר את החריגה.'};const open=short(state.settings?.opening_time||'07:30'),close=short(closingTimeForDate(sh.shift_date)),start=mins(sh.start_time)<mins(open)?open:short(sh.start_time),end=mins(sh.end_time)>mins(close)?close:short(sh.end_time);if(mins(end)<=mins(start))return{unsupported:true,group:g,reason:'לא ניתן ליישר את שעות השיבוץ לטווח תקין.'};return{type:'patch',group:g,shift:sh,start,end,title:'יישור שעות השיבוץ',change:`${short(sh.start_time)}–${short(sh.end_time)} ← ${start}–${end}`,detail:'רק הזמן שמחוץ לשעות פעילות המעון יוסר.',reasons:['אותו עובד/ת','אותה כיתה','ללא שינוי בתוך שעות הפעילות'],score:96};}
  async function build(g){const codes=new Set(originals(g).map(x=>x?.code).filter(Boolean));if([...codes].some(x=>COVER.has(x))||COVER.has(g?.code))return coverageProposal(g);if(codes.has('outside_opening_hours')||g?.code==='outside_opening_hours')return hoursProposal(g);if([...codes].some(x=>REPLACE.has(x))||REPLACE.has(g?.code))return replacementProposal(g);return{unsupported:true,group:g,reason:'לסוג החריגה הזה אין תיקון אוטומטי שאני יכול לבצע בלי סיכון ליצירת בעיה חדשה.'};}

  function render(p){const b=document.querySelector('#v037Body'),a=document.querySelector('#v037Actions');if(p.unsupported){b.innerHTML=`<div class="v037-box"><h4>לא נמצא תיקון אוטומטי בטוח</h4><p>${escapeHtml(p.reason)}</p></div>`;a.innerHTML='<button class="ghost-btn" type="button" data-v037-close>סגירה</button><button class="secondary-btn" type="button" data-v037-focus-current>הצג בשיבוץ</button>';return;}const tags=(p.reasons||[]).filter(Boolean).slice(0,4).map(x=>`<span>${escapeHtml(x)}</span>`).join('');b.innerHTML=`<div class="v037-box"><div><h4>${escapeHtml(p.title)}</h4><p>${escapeHtml(p.detail)}</p></div><div class="v037-change"><small>השינוי המוצע</small><br><strong>${escapeHtml(p.change)}</strong></div>${tags?`<div class="v037-tags">${tags}</div>`:''}<small>שום דבר עדיין לא השתנה. רק אישור מפורש יבצע את התיקון, ואז בדיקות התקינות ירוצו מחדש.</small></div>`;a.innerHTML='<button class="ghost-btn" type="button" data-v037-close>ביטול</button><button class="primary-btn" type="button" data-v037-apply>אשר ועדכן שיבוץ</button>';}
  async function openProposal(id){const g=state.v032ValidationGroupMap?.get(id);if(!g)return showToast('פרטי החריגה השתנו. רעננו את הבדיקה.','error');const d=ensureDialog();proposal=null;document.querySelector('#v037Body').innerHTML='<div class="v037-loading">מחפש את הפתרון המתאים ביותר…</div>';document.querySelector('#v037Actions').innerHTML='<button class="ghost-btn" type="button" data-v037-close>ביטול</button>';if(!d.open)d.showModal();try{proposal=await build(g);}catch(e){proposal={unsupported:true,group:g,reason:e?.message||'לא ניתן לחשב כרגע הצעה בטוחה.'};}render(proposal);}

  async function apply(btn){if(!proposal||proposal.unsupported)return;const published=isPublishedWeekDate(proposal.date||proposal.shift?.shift_date);setBusy(btn,true,'מעדכן…');try{if(proposal.type==='suggest'){const c=proposal.candidate;await apiFetch('/api/shifts',{method:'POST',body:{action:'apply_suggestion',target_shift_id:proposal.shiftId||null,candidate_id:c.employee_id,candidate_type:c.candidate_type||'direct',source_shift_id:c.source_shift_id||null,shift_date:proposal.date,class_id:proposal.classId,start_time:proposal.start,end_time:proposal.end,shift_role:c.suggested_role||proposal.role||'staff',public_note:proposal.shiftId?`מחליף/ה במקום ${proposal.old} · תיקון מבדיקת תקינות`:'תיקון מבדיקת תקינות'}});}else{const sh=proposal.shift;await apiFetch('/api/shifts',{method:'PATCH',body:{id:sh.id,shift_date:sh.shift_date,class_id:sh.class_id,employee_id:sh.employee_id,start_time:proposal.start,end_time:proposal.end,shift_role:sh.shift_role,public_note:sh.public_note||null}});}document.querySelector('#v037Dialog')?.close();state.shiftSuggestionCache?.clear?.();state.scheduleIssuesOpen=true;await refreshScheduleWeek({force:true});if(typeof window.__hadasV0345EnsureValidation==='function')await window.__hadasV0345EnsureValidation({force:true});renderSchedule();showToast('התיקון הוחל ובדיקות התקינות עודכנו','success');if(published)showPostPublishChangePrompt({title:'תיקון בוצע בשבוע שכבר פורסם',message:'התיקון נשמר כטיוטה. יש לפרסם אותו כדי שהצוות יראה את השינוי.'});}catch(e){showToast(e?.message||'לא ניתן להחיל את התיקון','error');}finally{setBusy(btn,false);}}

  document.addEventListener('click',e=>{const s=e.target.closest?.('[data-v037-suggest]');if(s){e.preventDefault();e.stopPropagation();openProposal(s.dataset.v037Suggest);return;}const ap=e.target.closest?.('[data-v037-apply]');if(ap){e.preventDefault();e.stopPropagation();apply(ap);return;}if(e.target.closest?.('[data-v037-close]')){e.preventDefault();e.stopPropagation();document.querySelector('#v037Dialog')?.close();return;}if(e.target.closest?.('[data-v037-focus-current]')&&proposal?.group){e.preventDefault();e.stopPropagation();document.querySelector('#v037Dialog')?.close();focusIssue(proposal.group);return;}const f=e.target.closest?.('[data-v032-focus]');if(f&&mobile()){const g=state.v032ValidationGroupMap?.get(f.dataset.v032Focus);if(g){e.preventDefault();e.stopImmediatePropagation();focusIssue(g);}}},true);

  function watch(){const p=document.querySelector('#scheduleWarnings');if(!p)return;validationObserver?.disconnect?.();validationObserver=new MutationObserver(()=>queueMicrotask(decorate));validationObserver.observe(p,{childList:true,subtree:true});decorate();}
  function enhance(){pinVersion();fixTools();decorate();}
  addStyles();ensureDialog();watch();matchMedia(MQ).addEventListener?.('change',fixTools);
  const prev=typeof renderSchedule==='function'?renderSchedule:null;if(prev)renderSchedule=function v037RenderSchedule(...args){const r=prev.apply(this,args);requestAnimationFrame(enhance);return r;};
  const root=document.querySelector('#schedulePanel')||document.body;new MutationObserver(()=>requestAnimationFrame(()=>{fixTools();if(!validationObserver||!document.querySelector('#scheduleWarnings'))watch();})).observe(root,{childList:true,subtree:true});
  enhance();
})();
