/* Hadas v0.32 — picker stability, automatic-week selector and calendar ranges */
(() => {
  if (window.__hadasV032UxInstalled) return;
  window.__hadasV032UxInstalled = true;

  function enhancePicker(){const target=document.querySelector('#shiftEmployeeOptionsList');if(!target)return;target.classList.add('v032-picker-stable');const filter=target.querySelector('.v031-picker-filter');if(filter)filter.classList.add('v032-sticky-picker-filter');const summary=target.querySelector('.v031-picker-summary');if(summary)summary.classList.add('v032-sticky-picker-summary');if(target.dataset.v032PickerEvents)return;target.dataset.v032PickerEvents='true';target.addEventListener('click',(e)=>{const b=e.target.closest('[data-v031-picker-filter]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();target.closest('.shift-employee-picker')?.classList.remove('v026-picker-collapsed');state.v031PickerFilter=b.dataset.v031PickerFilter;const top=target.scrollTop;renderShiftEmployeePicker();requestAnimationFrame(()=>{const next=document.querySelector('#shiftEmployeeOptionsList');next?.closest('.shift-employee-picker')?.classList.remove('v026-picker-collapsed');if(next)next.scrollTop=Math.max(0,Math.min(top,next.scrollHeight-next.clientHeight));enhancePicker();});},true);}
  const oldPicker=renderShiftEmployeePicker;renderShiftEmployeePicker=function(...args){const r=oldPicker(...args);requestAnimationFrame(enhancePicker);return r;};enhancePicker();

  function weekQuick(){const picker=document.querySelector('.auto-week-picker'),select=document.querySelector('#autoScheduleWeek');if(!picker||!select)return;picker.querySelectorAll('.v027-auto-week-quick').forEach((x)=>x.remove());let quick=picker.querySelector('.v032-auto-week-quick');if(!quick){quick=document.createElement('div');quick.className='v032-auto-week-quick';picker.insertBefore(quick,select);}const now=startOfWeek(new Date()),defs=[[-1,'שבוע שעבר'],[0,'השבוע'],[1,'שבוע הבא'],[2,'בעוד שבועיים']];quick.innerHTML=defs.map(([offset,label])=>{const start=addDays(now,offset*7),end=addDays(start,5),value=dateISO(start);return`<button type="button" data-v032-auto-week="${value}" class="${select.value===value?'active':''}"><strong>${label}</strong><small>${formatDate(start,{day:'2-digit',month:'2-digit'})}–${formatDate(end,{day:'2-digit',month:'2-digit'})}</small></button>`;}).join('');let info=picker.querySelector('.v032-auto-week-selected');if(!info){info=document.createElement('div');info.className='v032-auto-week-selected';select.insertAdjacentElement('afterend',info);}if(select.value){const start=parseDateValue(select.value);info.innerHTML=`<span>השבוע שנבחר</span><strong>${DAY_NAMES[start.getDay()]} ${formatDate(start,{day:'2-digit',month:'2-digit'})} – ${formatDate(addDays(start,5),{day:'2-digit',month:'2-digit',year:'numeric'})}</strong>`;}const label=picker.querySelector(':scope > span');if(label)label.textContent='בחירת שבוע לשיבוץ';}
  const auto=document.querySelector('#autoScheduleBtn');if(auto&&!auto.dataset.v032Installed){const b=auto.cloneNode(true);b.dataset.v032Installed='true';auto.replaceWith(b);b.addEventListener('click',(e)=>{e.preventDefault();e.stopImmediatePropagation();openAutoScheduleDialog();const select=document.querySelector('#autoScheduleWeek'),shown=dateISO(startOfWeek(state.weekStart));if(select&&[...select.options].some((o)=>o.value===shown))select.value=shown;renderAutoScheduleDateChoices();weekQuick();},true);}
  const dialog=document.querySelector('#autoScheduleDialog');if(dialog&&!dialog.dataset.v032Weeks){dialog.dataset.v032Weeks='true';dialog.addEventListener('click',(e)=>{const b=e.target.closest('[data-v032-auto-week]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const select=document.querySelector('#autoScheduleWeek');if(!select)return;select.value=b.dataset.v032AutoWeek;renderAutoScheduleDateChoices();select.dispatchEvent(new Event('change',{bubbles:true}));weekQuick();},true);document.querySelector('#autoScheduleWeek')?.addEventListener('change',()=>requestAnimationFrame(weekQuick));}

  function dates(startValue,endValue){const start=parseDateValue(startValue),end=parseDateValue(endValue||startValue);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime()))throw new Error('יש לבחור תאריכים תקינים');if(end<start)throw new Error('תאריך הסיום חייב להיות אחרי תאריך ההתחלה');const out=[];for(let d=new Date(start);d<=end;d=addDays(d,1)){out.push(dateISO(d));if(out.length>31)throw new Error('ניתן להגדיר עד 31 ימים בפעולה אחת');}return out;}
  function syncRange(){const form=document.querySelector('#calendarForm');if(!form)return;const general=form.elements.event_type?.value==='general_day_off',editing=Boolean(form.elements.id?.value);let field=form.querySelector('.v032-general-range-field');if(!field){const date=form.elements.event_date,label=date?.closest('label');if(!label)return;field=document.createElement('label');field.className='v032-general-range-field hidden';field.innerHTML='<span>עד תאריך</span><input name="event_end_date" type="date" /><small>אופציונלי — לבחירת כמה ימים רצופים ביחד.</small>';label.insertAdjacentElement('afterend',field);field.querySelector('input').addEventListener('change',syncRange);date.addEventListener('change',syncRange);}field.classList.toggle('hidden',!general||editing);const start=form.elements.event_date?.value||'',end=field.querySelector('input');if(end){end.min=start;if(general&&!editing&&start&&(!end.value||end.value<start))end.value=start;if(!general)end.value='';}let hint=form.querySelector('.v032-general-range-hint');if(general&&!editing&&!hint){hint=document.createElement('div');hint.className='v032-general-range-hint';hint.innerHTML='<strong>אפשר לבחור כמה ימים יחד</strong><span>בחרו תאריך התחלה ותאריך סיום. כל הימים בטווח יוגדרו כימי חופש כלליים בפעולה אחת.</span>';field.insertAdjacentElement('afterend',hint);}else if((!general||editing)&&hint)hint.remove();}
  const oldOpen=openCalendarDialog;openCalendarDialog=function(...args){const r=oldOpen(...args);requestAnimationFrame(syncRange);return r;};document.querySelector('#calendarForm')?.addEventListener('change',(e)=>{if(e.target.name==='event_type')requestAnimationFrame(syncRange);});
  document.addEventListener('submit',async(e)=>{const form=e.target;if(!(form instanceof HTMLFormElement)||form.id!=='calendarForm'||form.elements.event_type?.value!=='general_day_off')return;e.preventDefault();e.stopImmediatePropagation();const button=form.querySelector('button[value="default"]');setBusy(button,true,'שומר ימים חופשיים…');try{const data=formObject(form);let result;if(data.id){data.event_type='general_day_off';data.general_day_off=true;result=await apiFetch('/api/calendar',{method:'POST',body:data,timeout:15000});}else{const selected=dates(data.event_date,data.event_end_date||data.event_date);result=await apiFetch('/api/calendar',{method:'POST',body:{action:'bulk_general_day_off',event_dates:selected,title:data.title||'יום חופשי כללי',description:data.description||''},timeout:18000});}document.querySelector('#calendarDialog')?.close();state.calendarCache?.clear?.();state.weekCache?.clear?.();state.v027GeneralDayOffMonths?.clear?.();state.v027GeneralDaysOff?.clear?.();await setCalendarMonth(state.calendarMonth);await refreshScheduleWeek({force:true});const count=Number(result.days||result.created_events||1),deleted=Number(result.deleted_shifts||0);showToast(`${count} ${count===1?'יום חופשי נשמר':'ימים חופשיים נשמרו'}${deleted?` · הוסרו ${deleted} שיבוצים`:''}`,'success');}catch(err){showToast(err.message,'error');}finally{setBusy(button,false);}},true);

  const oldRender=renderSchedule;renderSchedule=function(...args){const r=oldRender(...args);requestAnimationFrame(()=>{enhancePicker();weekQuick();});return r;};
  syncRange();weekQuick();
})();
