(() => {
  const card=document.getElementById('pushSettingsCard'), button=document.getElementById('pushToggleBtn'), status=document.getElementById('pushStatusText');
  if(!card||!button||!status)return;
  const supported='serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window;
  const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
  const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
  let registration=null,currentSubscription=null;
  function b64(value){const padding='='.repeat((4-value.length%4)%4),raw=atob((value+padding).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));}
  async function api(path,options={}){const response=await fetch(path,{method:options.method||'GET',credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{})},body:options.body?JSON.stringify(options.body):undefined});let data={};try{data=await response.json();}catch{}if(!response.ok)throw new Error(data.error||'הפעולה נכשלה');return data;}
  function render(state,text){card.dataset.state=state;status.textContent=text;button.textContent=state==='active'?'כיבוי התראות':'הפעלת התראות';button.dataset.action=state==='active'?'disable':'enable';button.disabled=state==='unsupported';}
  async function ensureRegistration(){if(!supported)return null;registration ||= await navigator.serviceWorker.register('/push-sw.js?v=0372',{scope:'/'});await navigator.serviceWorker.ready;return registration;}
  async function refresh(){if(!supported)return render('unsupported','המכשיר או הדפדפן הזה אינם תומכים בהתראות Web Push.');if(isIOS&&!standalone())return render('warning','באייפון: לחצו שיתוף → „הוספה למסך הבית”, פתחו את מעון הדס מהאייקון ואז הפעילו התראות.');try{const reg=await ensureRegistration();currentSubscription=await reg.pushManager.getSubscription();if(currentSubscription&&Notification.permission==='granted')return render('active','ההתראות פעילות במכשיר הזה. שיבוצים, תוצאות בקשות והודעות חשובות יכולים להגיע גם כשהמערכת סגורה.');if(Notification.permission==='denied')return render('warning','ההתראות חסומות בהגדרות המכשיר/הדפדפן. יש לאפשר אותן בהגדרות ואז לנסות שוב.');render('idle','קבלו שיבוצים, תוצאות בקשות והודעות חשובות גם כשהמערכת סגורה.');}catch{render('warning','לא ניתן לבדוק כרגע את מצב ההתראות. אפשר לנסות שוב בעוד רגע.');}}
  async function enable(){if(isIOS&&!standalone())return refresh();button.disabled=true;button.textContent='מפעיל…';try{const info=await api('/api/push');if(!info.available||!info.publicKey)throw new Error('שירות ההתראות אינו זמין כרגע');if(await Notification.requestPermission()!=='granted')throw new Error('לא ניתנה הרשאה להתראות');const reg=await ensureRegistration();currentSubscription=await reg.pushManager.getSubscription()||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64(info.publicKey)});const json=currentSubscription.toJSON();await api('/api/push',{method:'POST',body:{action:'subscribe',endpoint:json.endpoint,p256dh:json.keys?.p256dh,auth:json.keys?.auth,device_label:isIOS?'iPhone / iPad':/Android/i.test(navigator.userAgent)?'Android':'דפדפן'}});render('active','ההתראות פעילות במכשיר הזה ✓');}catch(e){render('warning',e.message||'לא ניתן להפעיל התראות כרגע.');}finally{button.disabled=false;}}
  async function disable(){button.disabled=true;button.textContent='מכבה…';try{const reg=await ensureRegistration();currentSubscription ||= await reg.pushManager.getSubscription();await api('/api/push',{method:'POST',body:{action:'unsubscribe',endpoint:currentSubscription?.endpoint||''}});if(currentSubscription)await currentSubscription.unsubscribe().catch(()=>{});currentSubscription=null;render('idle','ההתראות כבויות במכשיר הזה. ניתן להפעיל אותן מחדש בכל עת.');}catch(e){render('warning',e.message||'לא ניתן לכבות התראות כרגע.');}finally{button.disabled=false;}}
  button.addEventListener('click',()=>button.dataset.action==='disable'?disable():enable());
  document.getElementById('notificationsBtn')?.addEventListener('click',()=>setTimeout(refresh,80));
  document.querySelector('#announcementForm [name="popup_on_login"]')?.addEventListener('change',e=>{if(e.target.checked){const push=document.querySelector('#announcementForm [name="send_push"]');if(push)push.checked=true;}});
  document.getElementById('announcementForm')?.addEventListener('submit',()=>{const popup=document.querySelector('#announcementForm [name="popup_on_login"]'),push=document.querySelector('#announcementForm [name="send_push"]');if(popup?.checked&&push)push.checked=true;},true);
  async function deepLink(){const params=new URLSearchParams(location.search),target=params.get('push');if(!target)return;for(let i=0;i<40;i++){const shell=document.getElementById('appShell');if(shell&&!shell.classList.contains('hidden')){const tab=target==='announcement'?'announcements':target==='request'?'requests':target==='schedule'?'schedule':null;if(tab)document.querySelector('[data-tab="'+tab+'"]')?.click();else if(target==='notifications')document.getElementById('notificationsBtn')?.click();history.replaceState({},'',location.pathname);return;}await new Promise(r=>setTimeout(r,250));}}
  ensureRegistration().catch(()=>{});deepLink().catch(()=>{});
})();