const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');

test('0.23 migration remains compatible under current release',()=>{assert.equal(JSON.parse(read('package.json')).version,'0.29.0');assert.match(read('handlers/health.js'),/0\.29\.0/);const sql=read('supabase/update-v0.23.0.sql');assert.match(sql,/hadas_request_messages/);assert.match(sql,/enable row level security/i);assert.match(sql,/revoke all.*anon,authenticated/i);assert.match(sql,/values\(1,'0\.23\.0','0\.23\.0'/);});
test('auto fix is preview editing rather than premature apply',()=>{const app=read('app.js'),shifts=read('handlers/shifts.js');assert.match(app,/autoIssueCorrectionHtml/);assert.match(app,/fixing/);assert.match(app,/revalidateAutomaticPreview/);assert.match(app,/manual_generated:state\.autoScheduleManualGenerated/);assert.doesNotMatch(app,/if\(issueAction==='fix'\)[\s\S]{0,300}applyAutomaticSchedule/);assert.match(shifts,/buildManualAutomaticPlan/);assert.match(shifts,/short_nonfixed_shift/);assert.match(shifts,/new Set\(\['understaffed','missing_leader','short_nonfixed_shift'\]\)/);});
test('request on behalf and conversation are server backed',()=>{const html=read('index.html'),app=read('app.js'),handler=read('handlers/requests.js'),schema=read('supabase/schema.sql');assert.match(html,/newEmployeeRequestBtn/);assert.match(html,/name="requester_id"/);assert.match(app,/requestConversationHtml/);assert.match(handler,/submitted_by_manager:onBehalf/);assert.match(handler,/action==='comment'/);assert.match(handler,/hadas_request_messages/);assert.match(schema,/submitted_by_manager boolean/);assert.match(schema,/create table if not exists public\.hadas_request_messages/);});
test('approved leave is derived into calendar with scoped visibility',()=>{const cal=read('handlers/calendar.js'),data=read('handlers/data.js');assert.match(cal,/approvedLeaveEvents/);assert.match(cal,/title==='סייעת מובילה'/);assert.match(cal,/source:'approved_leave'/);assert.match(data,/calendarVisibleLeave/);assert.match(data,/source:'approved_leave'/);});
test('shift role is derived from employee and not manually selected',()=>{const html=read('index.html'),app=read('app.js'),handler=read('handlers/shifts.js');assert.match(html,/type="hidden" name="shift_role"/);assert.doesNotMatch(html,/תפקיד בשיבוץ הזה/);assert.match(app,/data\.shift_role=suggestedShiftRoleForEmployee/);assert.match(handler,/payload\.shift_role=.*teacher/);});
test('schedule hours use LTR hyphen and PDF colors absence states',()=>{const app=read('app.js');assert.match(app,/time-value[^`]*\$\{end \? `-\$\{/);assert.match(app,/day_off_worked/);assert.match(app,/#edf9f1/);assert.match(app,/#fff0f0/);assert.match(app,/isolateCanvasLtr\(`\$\{trimTime\(shift\.start_time\)\}-\$\{trimTime\(shift\.end_time\)\}`\)/);});
test('schedule is denser and staffing steppers cannot escape cards',()=>{const css=read('styles.css');assert.match(css,/schedule-table\{min-width:980px/);assert.match(css,/schedule-cell\{min-height:136px/);assert.match(css,/staffing-stepper-card\{grid-template-columns:auto minmax\(0,1fr\);overflow:hidden/);assert.match(css,/number-stepper\{max-width:100%;min-width:0/);});
